# Generated by Django 5.2.4 on 2025-08-02 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("dental_history", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الطبيب المعالج",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=50, null=True)),
                ("times_per_day", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "time_of_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "صباحاً"),
                            ("noon", "ظهراً"),
                            ("evening", "مساءً"),
                            ("night", "ليلاً"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Radiograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photoRadiograph/"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiographs",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToothTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("healthy", "سليم"),
                            ("cavity", "نخر"),
                            ("filled", "حشوة"),
                            ("crowned", "تاج"),
                            ("root_canal", "معالجة لب"),
                            ("extracted", "مقلوع"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "treatment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("filling", "حشو"),
                            ("extraction", "قلع"),
                            ("cleaning", "تنظيف"),
                            ("crown", "تاج"),
                            ("root_canal", "معالجة لب"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tooth_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photoTooth/"),
                ),
                (
                    "treatment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
